baseurl = "https://lemonilemon.github.io/"
title = "lemonilemon's Blog"
theme = "hugo-coder"
# languageCode = "zh-TW"
enableEmoji = true
defaultContentLanguage = "en"
languageCode = "en-US"
# [languages]
#     [languages.zh]
#     languageName =  "Chinese"
#     languageCode = "zh-TW"
#         [languages.zh.params]
#             reading_speed = 500
#     [languages.en]
#         languageCode = "en-US"
#         languageName = "English"
#         [languages.en.params]
#             reading_speed = 212

[pagination]
pagerSize = 6

[services]
[services.disqus]
shortname = "lemonilemon"

[markup.highlight]
style = "github-dark"

[params]
  author = "lemonilemon"
  keywords = "blog,developer,personal"
  info = "Tech-Tinkering Code Alchemist"
  dateFormat = "January 2, 2006"
  description = "lemonilemon's personal website"
  gravatar = "imlemonilemon@gmail.com"
  colorScheme = "auto"
  since = 2025
  enableTwemoji = true
  hidecolorschemetoggle = false
  maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/lemonilemon/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
